### ISSUE TITLE
Fix: Need to customise LICENSE.md

### ISSUE THREAD

**Issue by AmanxUpadhyay** [AmanxUpadhyay/GODL1KE#1]
We want to update the License according to our project need. As it's not a public project. We want to use standard private License. I have already added the needed Template but we need to modify it a bit.

**Comment by imAkshayDarji** [comment]
Hi, I will be doing it. Please assign me.

**Comment by AmanxUpadhyay** [comment]
Thank you for taking this responsibility. You are now assigned.

**Comment by AmanxUpadhyay** [comment]
@akshay5512 Did you started working on it?

**Comment by imAkshayDarji** [comment]
@AmanxUpadhyay It's already done...

**Comment by AmanxUpadhyay** [comment]
Thanks for contributing
